version: "1.0"
type: route
data:
  url: "/services/frpc/settings"
  title: _("Settings")
  editing: true
  notificationTitle: _("Updated FRP client settings.")
  component: omv-services-frpc-settings-form-page
